from typing import List
from ..types.evaluation_result import EvaluationResult
from genetic_algorithm.objects.population import Population

import jax.numpy as jnp

def replace_population(
    parents: List[EvaluationResult],
    offspring: List[EvaluationResult],
    elite_frac: float = 0.1,
) -> Population:
    """
    Build the next generation population by preserving the best elites
    from the current population and filling the remaining slots with
    offspring.

    Args:
        parents:  Evaluated results of the current population.
        offspring: Evaluated (or at least structure‑containing) results
                   of the offspring generated by crossover/mutation.
        elite_frac: Fraction of the population to keep as elites
                    (the individuals with the smallest cost).

    Returns:
        A new Population object with the same size as the original
        population.
    """
    pop_size = len(parents)
    if pop_size == 0:
        # Edge case: empty population – return empty Population
        return Population(
            materials=jnp.empty((0, 0), dtype=jnp.int8),
            thicknesses_m=jnp.empty((0, 0), dtype=jnp.float32),
            active_mask=jnp.empty((0, 0), dtype=bool),
            free_thickness_mask=jnp.empty((0, 0), dtype=bool),
            free_material_mask=jnp.empty((0, 0), dtype=bool),
        )

    elite_count = int(elite_frac * pop_size)
    elite_count = max(0, min(elite_count, pop_size))

    # Sort parents by cost (ascending) and select elites
    sorted_parents = sorted(parents, key=lambda r: r.cost)
    elites = sorted_parents[:elite_count]

    # Number of offspring to take
    needed_offspring = pop_size - elite_count
    # Take the first needed_offspring from the offspring list
    selected_offspring = offspring[:needed_offspring]

    # Combine structures
    new_structures = [e.structure for e in elites] + [o.structure for o in selected_offspring]

    # If by any chance we don't have enough, fill with copies of the best elite
    # (should not happen in a correct GA pipeline)
    while len(new_structures) < pop_size:
        new_structures.append(elites[0].structure)

    # Stack into Population arrays
    materials = jnp.stack([s.materials for s in new_structures])
    thicknesses_m = jnp.stack([s.thicknesses_m for s in new_structures])
    active_mask = jnp.stack([s.active_mask for s in new_structures])

    # The free masks are identical for all structures; take from the first one
    free_thick = new_structures[0].free_thickness_mask
    free_mat = new_structures[0].free_material_mask
    free_thickness_mask = jnp.repeat(free_thick[None, :], pop_size, axis=0)
    free_material_mask = jnp.repeat(free_mat[None, :], pop_size, axis=0)

    return Population(
        materials=materials,
        thicknesses_m=thicknesses_m,
        active_mask=active_mask,
        free_thickness_mask=free_thickness_mask,
        free_material_mask=free_material_mask,
    )